### PR TITLE
Feature/simple pagination 232

### PR DESCRIPTION
**Pull request by akdetrick**
Updated pagination styles. 
In this version we always show up to **4** pages. The circles for hover/selected states are larger in larger viewports.

screen shot 2016-01-19 at 4 23 27 pm
screen shot 2016-01-19 at 4 23 46 pm

### CODE REVIEW

**Comment by byronhulcher** [comment]
What if instead of removing the prev/next arrows we kept them in with a `visibility: hidden`. I'm not a huge fan of how the spacing is redone when you add/remove the arrows, i think it doesn't look as nice visually when moving between pages, and could confuse your thumb when tapping quickly.  Maybe instead we could retain the layout/spacing of the arrows, but just hide them and disable them for cases where they shouldn't be there?

**Comment by akdetrick** [comment]
@byronhulcher : Agreed. A consistent touch position will be important for touch devices. This also allows us to populate the previous/next list items with accessible text for screen readers.

**Comment by mperrotti** [comment]
Two pieces of feedback
1: I'm a little worried about the tap targets being too small on mobile. What if we only showed the current page number with the prev/next arrows?
2: Are we using unicode arrows? I actually don't mind them too much, but I'd prefer real icons

**Comment by akdetrick** [comment]
We're using unicode arrows in the example because icons are not within the responsibility of Sassquatch.

I can make a note of that in the documentation.

**Comment by akdetrick** [comment]
**Updated screenshots**

screen shot 2016-01-20 at 2 55 04 pm
screen shot 2016-01-20 at 2 55 35 pm

**Comment by akdetrick** [comment]
updated small screen version (hide selected states for viewports below `medium`)
screen shot 2016-01-25 at 3 39 13 pm

**Pull request merged**
